[project]
name = "z-yt-audios"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bark>=0.1.5",
    "scipy>=1.16.3",
    "zensical>=0.0.7",
]
